### PR TITLE
fix(report): remove @path property from iframes and images

### LINKED ISSUE #64: Make sure absolute paths are discarded from the report?
When building the report, Ace resolves relative paths (e.g. to EPUB’s resources like images) to absolute paths. This could be a privacy/security vulnerability, notably in a server-side scenario.

When building the final report, Ace should make sure to discard all these absolute path references.

### PR DESCRIPTION
**Pull request by marisademeglio**
The json data is scrubbed clean of @path properties after the images are copied. If we aren't storing the report on disk, the json data is scrubbed before it gets written to the console.

I'd rather separate out any data that needs to be copied and not have it stored in the report in the first place, but that would involve some redesign. Maybe a good idea for the future.

Closes #64

### CODE REVIEW

File: packages/ace-report/src/report-builders.js [hunk 1]
```diff
@@ -110,6 +110,12 @@ class ReportBuilder {
   build() {
     return this._json;
   }
+  // run the function on the given item under _json.data
+  cleanData(key, fn) {
```
Comment (rdeltour) [inline packages/ace-report/src/report-builders.js]: I'm wondering if this is worth being added as a utility to `ReportBuilder`.
Do we plan other use? Or outside the `data` section?
If we're to keep it, maybe `transformData` is a more explicit function name.

Comment (marisademeglio) [reply packages/ace-report/src/report-builders.js]: Ace needed some way to remove `path` after the images get copied but before saving/printing output, and putting it in `ReportBuilder` is the only safe place to access `_json`. We could put all the logic there but I liked it better as as visitor-style function (albeit not very generic), because `ReportBuilder` doesn't know anything about the details of the `data` section in the first place.

Like I said, I'd rather not put temporary data into the report at all (or maybe it could be more explicitly in a `temp` section, but this works for now).

**Comment by marisademeglio** [comment]
Yes, I noticed that. I'd have cancelled this PR, but I wanted your comments about the code.

File: packages/ace-report/src/report-builders.js (hunk 1 above)
Comment (rdeltour) [reply packages/ace-report/src/report-builders.js]: all right, makes sense!

**Comment by rdeltour** [comment]
No need to cancel the PR as far as I can see. We can probably figure out the tests issue and add to the PR.
In such cases, I would either force-push to the PR branch to amend the commit, or alternatively push commits as they come and squash everything when merging.
